name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ok
      name: ok
      url: https://github.com
    steps:
      - run: echo 1
